notifications:
  email: false
deploy:
  provider: pypi
  user: szmingyao
  password:
    secure: ir8Gb03bHJVv2grgBHXppUPzrASZb7nWlLNwhg9YiIYu6UC3KZhj25ZX3WaQKWG7eRygp22KepvH4vk2aPHM85uifD9j8R8Y7MhKANH1032H44gJI+zQeGybqFKL/c8rM2jbVbDrJOXABE6KmDoXLIUpiqj2JPkEtg8FImRPMHxRdjEc6GWAr0MAtYux81x0pgirVPAJMNrq8JsaczfmWC+9ZcHau0gWrTucJzpKEfTHZQ6+S6LeAdIdkHPoTvlYfIOB3vDWSoq9uC6RtY2i5FYO4CSmOkzFISn2JqaYJqEMVEXvScp4BVv7ArmF+z08EOWJ6qB8LvBcBt2MZ2iOEAV/8lB15o2kzx3Tw7oRYHZ4VU0oAWXU/mIgbuU+GUHLmFwj1XqPKe+JFsVT8oRJbHOMnjeCTqcx9U/k4rXbJdV9dO+QCo5VnoXEwMNMUYQSMDLBCdVPIClGBsWwvxxM1S+rfzIL9OUGa0WHu2XXPEpFNAQd4HO1qho6+s213HRUVcRqB+gQ4tUmF2kwtKq68jjFoIjtP74WzQwFc918gv6s3o9kj/8SjKMdCnIlde027bvwGg3MQ/2zZnQdLx1HeaOjASovUieQfejRjHu7dNIfDBNjFBGwe/2Wi8FzLBFo/KKUwSaba6dSv7fjf4er1o70fnQPDnH4WPXvrK6ftHk=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: production
language: python
python: 3.5
sudo: required
dist: trusty
services: docker
matrix:
  exlclude:
  - python: 3.5
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/code $DOCKER_IMAGE
  $PRE_CMD /code/scripts/docker_build.sh    ; fi
- ls dist/
