notifications:
  email: false
deploy:
  provider: pypi
  user: szmingyao
  password:
    secure: WMeHX/E6aYxyjqBFMJYcP+VZzbLslOdJgrBxOlEFrr0UQemfhFSXbYPFbaQtB+jrO1FSvKRrMi7GcMWDqAWalZTtPAuI4Hto27TzfHp6314XZtOPXuYO0ZaBgNwtBhySB11VL8h/hIuwJ610MRIKpZ8MIF4QA5ThT2RppzUMXGTs2kYatG3uGlVc41pJXCjYxI27Y6X4YeLKVhabdPT6uRNE5ZXHR4ZKVyEeWypn0ZKd2aKagEIcVy/LerTH7/XxDujsp89xivwGsLKM548nL2Iv3KHTjA0/nNJCIbtfk0uYe2CeVKsdzOsqoD8pbehGKxPh6cafuaNdQ3VNVW+xER8oHJBKYbMZuaCl+68FONWuCRZwOWbkptXP9BAK4XU1LwK5EiESD52CMSbOqxiCSatR+XhXSU2DWnuHxGHsFtEJpvwHUuABk2EpEamjimkikV2Dn4nzY9G8JCTrV+9TI5QVp/DVXLRiI3nIyRjhvnKXao3DKnfnMythKjZEJb3yvpicaQfyKzK2y12poL/eajHjMMBxBXplGK0kqY+bNK2pq+yaOycXgXdC52yTMAC0CqnzlOSWa77R9XWNqcCgKS3fKTT5UlWh3C2a9q6YXCIsjq3T1/Qri4Bc84sZQcr9a/+RnyvFg0W/cob6Qon89DbvmywsO7Q3fT4mDvJXO54=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: production
language: python
python: 3.5
sudo: required
dist: trusty
services: docker
matrix:
  exlclude:
  - python: 3.5
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/code $DOCKER_IMAGE
  $PRE_CMD /code/scripts/docker_build.sh    ; fi
- ls dist/
