notifications:
  email: false
deploy:
  provider: pypi
  user: szmingyao
  password:
    secure: lnjqFyeMjpiNrUPt8xiy/nshkV3X8//q3psTyqBxwqDLoblp3CJ7sCsCbjFkltSH3P5NW+8ZECMILsufRfJt+3LpFLrSAq6hjItZMwS+j2QHoQXQylawwryV+0lKvzFo1ZQ8e+9LyFQW+JjFb4daS3FfB44jNM5lhXE5a9ixDT/EOuVrwy/ulrA1dc1JaWyZXcWJYi1sKb+pYHgPoMGifG/Mb9V0C03LazIK3NinAI6S61E43XB34ljTfh2ERDewDhes1XefEIQuDSruG192fh10g42XoTuO1F2duilOIrhoMnx1LC+KfREywoLvjuA2w3vK+ugeMEXXyfcPZGtm9+0j/1MG2ORoCA6seEiovwEctXpKeUHKSPiriWX3plo3scyBRSnoR1Ngd+o/q5nkyphpRAqdaXwN51cMkpUt6O3x7MHGwUepaKkicM5VZcLtKUuYNob9NtpvSFaE2rPcsKXfGtQk753prWox0D7b+45ZEo+QIq3GbLV9p8/fCMZ/agtY3dOMLMgfWa3ENHxfwZTWqlHt0NWGRWQFpYlhQN7TyndprvTBmbF9mEOoj7e8RPcTsL8QtpAIbj0GfCLY6WuPneFpNjn9zp3TOihC9BTI7YhXAYB5YYhnmNWl5Dum0vax/MopjwGcekkQeZbd/L4WvhpkDWqqLKj9obzGHlw=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: production

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/code $DOCKER_IMAGE
  $PRE_CMD /code/scripts/docker_build.sh    ; fi
- ls dist/
