notifications:
  email: false
deploy:
  provider: pypi
  user: szmingyao
  password:
    secure: POTc6Tt2Q7P/FO1JlkpPhMB7UJumtklEdTY22wLf9TaeeftK3xYRKVDHwdulwUAf1SczhlaxEGf4uNSEK4z/5OvoMLtcIUdpXlm9nDONcknG4LGdD2RgyeK7h5Q0Yms1VRKvwcOep1ECT2qyG+f+AoDL5H41xBYbpmEC7QxKUBWGs2NE5I4bgaC4dh+ex4YFkRrC3ctIpMFFnsD042IX59M2iObZV77V5w0YQyB304/TMGH1hD37k+uY3homl0jPvz7XYmxq9ABD9d+bce40keZ1biypkdSauqgZmCziR1LS/ZUOc6dkDDBNbB3em80UtpbmOFRAi1upmkwIMI/MoLY+5EwsXWqWXZi4UoyNp3JRPdh7EaZZlVI9OBlFxQR2YxkQ7o8sgsqutlHY8X/C/D6Kw7f8phhpuI+Ksk5JdcOwKKseurEmd+BalTdSK7bf6qGYv/hoei7HkYhw8Zw+I1klB7c75ejcQhd83UoFuXZZJOgRiDvPsKfwwZNTQEnS0RM5jUyuNbvi4QQ9usF2eUE4rvrj2G/Zz/vVa4uQZj4ZHncyMckFucP5KC0NMHhMV7CPuDRTlTUe1QqQ6ZKev+fbVFAXqIxjV61d1D0CtOuUSDHzRapmAnOyckR5hSp0zh/xINa3BrcLa0P3weIvN99IO88R5sTnxTo5L7B1alE=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: production
language: python
python: 3.5
sudo: required
dist: trusty
services: docker
matrix:
  exlclude:
  - python: 3.5
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull $DOCKER_IMAGE; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v `pwd`:/code $DOCKER_IMAGE
  $PRE_CMD /code/scripts/docker_build.sh    ; fi
- ls dist/
